name: Vercel Deploy

on:
  push:
    branches:
      - main # Deploys to production on the main branch.
      - staging # Deploys a preview build on the staging branch.

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your project's Node.js version.
          
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Deploy to Production when pushing to main
            npx vercel --prod --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --scope $
          elif [[ "${{ github.ref }}" == "refs/heads/staging-branch" ]]; then
            # Deploy Preview when pushing to staging
            npx vercel --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --scope $
          fi
