name: Vercel Deploy

on:
  push:
    branches:
      - main # Deploys to production on the main branch.
      - staging # Deploys a preview build on the staging branch.
  pull_request:
    branches:
      - main # Triggers a build when a PR is opened against main.

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your project's Node.js version.

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      # Deploy to Vercel Production when pushing to main
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
        continue-on-error: true # Allow workflow to continue on failure

      # Deploy to Vercel Preview when pushing to staging
      - name: Deploy to Vercel (Preview)
        if: github.ref == 'refs/heads/staging'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        continue-on-error: true # Allow workflow to continue on failure

      # Rollback on Failure for Production
      - name: Rollback Production Deployment
        if: failure() && github.ref == 'refs/heads/main'
        run: |
          echo "Production deployment failed. Rolling back to previous deployment..."
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --rollback

      # Rollback on Failure for Preview (Staging)
      - name: Rollback Preview Deployment
        if: failure() && github.ref == 'refs/heads/staging'
        run: |
          echo "Staging deployment failed. Rolling back to previous deployment..."
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} --rollback



